<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        $categories = [
            [
                'id' => 136,
                'company_id' => 1,
                'name' => 'Gross Profit',
                'parent_id' => null,
                'type' => 'income',
                'sort' => 1,
                'account' => null,
            ],
            [
                'id' => 137,
                'company_id' => 1,
                'name' => 'Operative Income',
                'parent_id' => null,
                'type' => 'income',
                'sort' => 2,
                'account' => null,
            ],
            [
                'id' => 138,
                'company_id' => 1,
                'name' => 'Earning Before Taxes',
                'parent_id' => null,
                'type' => 'income',
                'sort' => 3,
                'account' => null,
            ],
            [
                'id' => 139,
                'company_id' => 1,
                'name' => 'Net Income',
                'parent_id' => null,
                'type' => 'income',
                'sort' => 4,
                'account' => null,
            ],
            [
                'id' => 1,
                'company_id' => 1,
                'name' => 'Income',
                'parent_id' => 136,
                'type' => 'income',
                'sort' => 5,
                'account' => null,
            ],
            [
                'id' => 2,
                'company_id' => 1,
                'name' => 'Direct Operational Cost',
                'parent_id' => 136,
                'type' => 'income',
                'sort' => 6,
                'account' => null,
            ],
            [
                'id' => 3,
                'company_id' => 1,
                'name' => 'Other Operational Cost',
                'parent_id' => 136,
                'type' => 'income',
                'sort' => 7,
                'account' => null,
            ],
            [
                'id' => 4,
                'company_id' => 1,
                'name' => 'Operating Expenses',
                'parent_id' => 137,
                'type' => 'income',
                'sort' => 8,
                'account' => null,
            ],
            [
                'id' => 5,
                'company_id' => 1,
                'name' => 'Depreciation and Amortization',
                'parent_id' => 137,
                'type' => 'income',
                'sort' => 9,
                'account' => null,
            ],
            [
                'id' => 6,
                'company_id' => 1,
                'name' => 'Financial Cost',
                'parent_id' => 138,
                'type' => 'income',
                'sort' => 10,
                'account' => null,
            ],
            [
                'id' => 7,
                'company_id' => 1,
                'name' => 'Other Income/Expenses',
                'parent_id' => 138,
                'type' => 'income',
                'sort' => 11,
                'account' => null,
            ],
            [
                'id' => 8,
                'company_id' => 1,
                'name' => 'Non-company related expenditures/Income',
                'parent_id' => 138,
                'type' => 'income',
                'sort' => 12,
                'account' => null,
            ],
            [
                'id' => 9,
                'company_id' => 1,
                'name' => 'Taxes',
                'parent_id' => 139,
                'type' => 'income',
                'sort' => 13,
                'account' => null,
            ],
            // Level 2
            // Income -> Parent 1
            [
                'id' => 10,
                'company_id' => 1,
                'name' => 'Income from Services',
                'parent_id' => 1,
                'type' => 'income',
                'sort' => 14,
                'account' => null,
            ],
            [
                'id' => 11,
                'company_id' => 1,
                'name' => 'Income from  equity Securities',
                'parent_id' => 1,
                'type' => 'income',
                'sort' => 15,
                'account' => null,
            ],
            [
                'id' => 12,
                'company_id' => 1,
                'name' => 'Income From Private equity Gains',
                'parent_id' => 1,
                'type' => 'income',
                'sort' => 16,
                'account' => null,
            ],
            [
                'id' => 13,
                'company_id' => 1,
                'name' => 'Income from Debt Securities',
                'parent_id' => 1,
                'type' => 'income',
                'sort' => 17,
                'account' => null,
            ],
            [
                'id' => 14,
                'company_id' => 1,
                'name' => 'Income from Cash Markets',
                'parent_id' => 1,
                'type' => 'income',
                'sort' => 18,
                'account' => null,
            ],
            [
                'id' => 15,
                'company_id' => 1,
                'name' => 'Income from IP',
                'parent_id' => 1,
                'type' => 'income',
                'sort' => 19,
                'account' => null,
            ],
            [
                'id' => 16,
                'company_id' => 1,
                'name' => 'Income from Cryptocurrency',
                'parent_id' => 1,
                'type' => 'income',
                'sort' => 20,
                'account' => null,
            ],
            [
                'id' => 17,
                'company_id' => 1,
                'name' => 'Other income',
                'parent_id' => 1,
                'type' => 'income',
                'sort' => 21,
                'account' => null,
            ],
            // Direct Operational Cost -> Parent 2
            [
                'id' => 18,
                'company_id' => 1,
                'name' => 'Associated Cost to investments',
                'parent_id' => 2,
                'type' => 'income',
                'sort' => 22,
                'account' => null,
            ],
            [
                'id' => 19,
                'company_id' => 1,
                'name' => 'Cost associated with intelectual property development',
                'parent_id' => 2,
                'type' => 'income',
                'sort' => 23,
                'account' => null,
            ],
            // Other Operational Cost -> Parent 3
            [
                'id' => 20,
                'company_id' => 1,
                'name' => 'Salary cost Services ',
                'parent_id' => 3,
                'type' => 'income',
                'sort' => 24,
                'account' => null,
            ],
            [
                'id' => 21,
                'company_id' => 1,
                'name' => 'Contribution to social insurance',
                'parent_id' => 3,
                'type' => 'income',
                'sort' => 25,
                'account' => null,
            ],
            [
                'id' => 22,
                'company_id' => 1,
                'name' => 'Other personnel expenses',
                'parent_id' => 3,
                'type' => 'income',
                'sort' => 26,
                'account' => null,
            ],
            // Operating Expenses -> Parent 4
            [
                'id' => 23,
                'company_id' => 1,
                'name' => 'Rent',
                'parent_id' => 4,
                'type' => 'income',
                'sort' => 27,
                'account' => null,
            ],
            [
                'id' => 24,
                'company_id' => 1,
                'name' => 'Maintenace, repairs,  replacem. of tangible assets',
                'parent_id' => 4,
                'type' => 'income',
                'sort' => 28,
                'account' => null,
            ],
            [
                'id' => 25,
                'company_id' => 1,
                'name' => 'Vehicle and transportation expenses',
                'parent_id' => 4,
                'type' => 'income',
                'sort' => 29,
                'account' => null,
            ],
            [
                'id' => 26,
                'company_id' => 1,
                'name' => 'Insurance for damage of items',
                'parent_id' => 4,
                'type' => 'income',
                'sort' => 30,
                'account' => null,
            ],
            [
                'id' => 27,
                'company_id' => 1,
                'name' => 'Utilities',
                'parent_id' => 4,
                'type' => 'income',
                'sort' => 31,
                'account' => null,
            ],
            [
                'id' => 28,
                'company_id' => 1,
                'name' => 'Administrative and IT costs',
                'parent_id' => 4,
                'type' => 'income',
                'sort' => 32,
                'account' => null,
            ],
            [
                'id' => 29,
                'company_id' => 1,
                'name' => 'Advertising',
                'parent_id' => 4,
                'type' => 'income',
                'sort' => 33,
                'account' => null,
            ],
            [
                'id' => 30,
                'company_id' => 1,
                'name' => 'Other expenses',
                'parent_id' => 4,
                'type' => 'income',
                'sort' => 34,
                'account' => null,
            ],
            // Depreciation and Amortization -> Parent 5
            [
                'id' => 31,
                'company_id' => 1,
                'name' => 'Depreciation and value adjustments of fixed assests',
                'parent_id' => 5,
                'type' => 'income',
                'sort' => 35,
                'account' => null,
            ],
            // Financial Cost -> Parent 6
            [
                'id' => 32,
                'company_id' => 1,
                'name' => 'Financial costs',
                'parent_id' => 6,
                'type' => 'income',
                'sort' => 36,
                'account' => null,
            ],
            // Other Income/Expenses -> Parent 7
            [
                'id' => 33,
                'company_id' => 1,
                'name' => 'Rental Income',
                'parent_id' => 7,
                'type' => 'income',
                'sort' => 37,
                'account' => null,
            ],
            [
                'id' => 34,
                'company_id' => 1,
                'name' => 'Gains on tangible fixed assets',
                'parent_id' => 7,
                'type' => 'income',
                'sort' => 38,
                'account' => null,
            ],
            // Non-company related expenditures/Income -> Parent 8
            [
                'id' => 35,
                'company_id' => 1,
                'name' => 'Non-company related expenditures',
                'parent_id' => 8,
                'type' => 'income',
                'sort' => 39,
                'account' => null,
            ],
            [
                'id' => 36,
                'company_id' => 1,
                'name' => 'Non-company related income',
                'parent_id' => 8,
                'type' => 'income',
                'sort' => 40,
                'account' => null,
            ],
            // Taxes -> Parent 9
            [
                'id' => 37,
                'company_id' => 1,
                'name' => 'Cantonal and municipal taxes',
                'parent_id' => 9,
                'type' => 'income',
                'sort' => 41,
                'account' => null,
            ],
            [
                'id' => 38,
                'company_id' => 1,
                'name' => 'Direct federal taxes',
                'parent_id' => 9,
                'type' => 'income',
                'sort' => 42,
                'account' => null,
            ],
            // Accounting Codes
            [
                'id' => 39,
                'company_id' => 1,
                'name' => 'Income from Services',
                'parent_id' => 10,
                'type' => 'income',
                'sort' => 43,
                'account' => 3400,
            ],
            [
                'id' => 40,
                'company_id' => 1,
                'name' => 'Revenue Dividends Income',
                'parent_id' => 11,
                'type' => 'income',
                'sort' => 44,
                'account' => 3410,
            ],
            [
                'id' => 41,
                'company_id' => 1,
                'name' => 'Revenue Unrealized gains in trading securities',
                'parent_id' => 11,
                'type' => 'income',
                'sort' => 45,
                'account' => 3415,
            ],
            [
                'id' => 42,
                'company_id' => 1,
                'name' => 'Earnings from short-term financial investments',
                'parent_id' => 11,
                'type' => 'income',
                'sort' => 46,
                'account' => 3420,
            ],
            [
                'id' => 43,
                'company_id' => 1,
                'name' => 'Realized gains in  Private equity Holdings',
                'parent_id' => 12,
                'type' => 'income',
                'sort' => 47,
                'account' => 3425,
            ],
            [
                'id' => 44,
                'company_id' => 1,
                'name' => 'Interest gains from AFS debt investments',
                'parent_id' => 13,
                'type' => 'income',
                'sort' => 48,
                'account' => 3430,
            ],
            [
                'id' => 45,
                'company_id' => 1,
                'name' => 'Realized gains on AFS debt invesments',
                'parent_id' => 13,
                'type' => 'income',
                'sort' => 49,
                'account' => 3435,
            ],
            [
                'id' => 46,
                'company_id' => 1,
                'name' => 'Return on bank deposits',
                'parent_id' => 14,
                'type' => 'income',
                'sort' => 50,
                'account' => 3440,
            ],
            [
                'id' => 47,
                'company_id' => 1,
                'name' => 'Exchange gains',
                'parent_id' => 14,
                'type' => 'income',
                'sort' => 51,
                'account' => 3445,
            ],
            [
                'id' => 48,
                'company_id' => 1,
                'name' => 'Other Interest gains',
                'parent_id' => 14,
                'type' => 'income',
                'sort' => 52,
                'account' => 3450,
            ],
            [
                'id' => 49,
                'company_id' => 1,
                'name' => 'Revenue from Royalties',
                'parent_id' => 15,
                'type' => 'income',
                'sort' => 53,
                'account' => 3455,
            ],
            [
                'id' => 50,
                'company_id' => 1,
                'name' => 'Revenue from IP sales',
                'parent_id' => 15,
                'type' => 'income',
                'sort' => 54,
                'account' => 3460,
            ],
            [
                'id' => 51,
                'company_id' => 1,
                'name' => 'Gains on Cryptocurrency holdings value',
                'parent_id' => 16,
                'type' => 'income',
                'sort' => 55,
                'account' => 3465,
            ],
            [
                'id' => 52,
                'company_id' => 1,
                'name' => 'Discount',
                'parent_id' => 17,
                'type' => 'income',
                'sort' => 56,
                'account' => 3490,
            ],
            [
                'id' => 53,
                'company_id' => 1,
                'name' => 'Rebates and price deductions',
                'parent_id' => 17,
                'type' => 'income',
                'sort' => 57,
                'account' => 3491,
            ],
            [
                'id' => 54,
                'company_id' => 1,
                'name' => 'Losses from receivables',
                'parent_id' => 17,
                'type' => 'income',
                'sort' => 58,
                'account' => 3495,
            ],
            [
                'id' => 55,
                'company_id' => 1,
                'name' => 'Costs of services',
                'parent_id' => 18,
                'type' => 'income',
                'sort' => 59,
                'account' => 4400,
            ],
            [
                'id' => 56,
                'company_id' => 1,
                'name' => 'Investments Comision',
                'parent_id' => 18,
                'type' => 'income',
                'sort' => 60,
                'account' => 4410,
            ],
            [
                'id' => 57,
                'company_id' => 1,
                'name' => 'Management fees',
                'parent_id' => 18,
                'type' => 'income',
                'sort' => 61,
                'account' => 4415,
            ],
            [
                'id' => 58,
                'company_id' => 1,
                'name' => 'Brokerage Comissions',
                'parent_id' => 18,
                'type' => 'income',
                'sort' => 62,
                'account' => 4420,
            ],
            [
                'id' => 59,
                'company_id' => 1,
                'name' => 'Management fees Private equity',
                'parent_id' => 18,
                'type' => 'income',
                'sort' => 63,
                'account' => 4425,
            ],
            [
                'id' => 60,
                'company_id' => 1,
                'name' => 'Interest from leveraged investments',
                'parent_id' => 18,
                'type' => 'income',
                'sort' => 64,
                'account' => 4430,
            ],
            [
                'id' => 61,
                'company_id' => 1,
                'name' => 'Bank investments comissions (Private Equity)',
                'parent_id' => 18,
                'type' => 'income',
                'sort' => 65,
                'account' => 4435,
            ],
            [
                'id' => 62,
                'company_id' => 1,
                'name' => 'Other Investments Comissions',
                'parent_id' => 18,
                'type' => 'income',
                'sort' => 66,
                'account' => 4440,
            ],
            [
                'id' => 63,
                'company_id' => 1,
                'name' => 'Labor fees',
                'parent_id' => 19,
                'type' => 'income',
                'sort' => 67,
                'account' => 3600,
            ],
            [
                'id' => 64,
                'company_id' => 1,
                'name' => 'Techological tools Cost',
                'parent_id' => 19,
                'type' => 'income',
                'sort' => 68,
                'account' => 3610,
            ],
            [
                'id' => 65,
                'company_id' => 1,
                'name' => 'Bank comissions',
                'parent_id' => 19,
                'type' => 'income',
                'sort' => 69,
                'account' => 3615,
            ],
            [
                'id' => 66,
                'company_id' => 1,
                'name' => 'Other incubation cost',
                'parent_id' => 19,
                'type' => 'income',
                'sort' => 70,
                'account' => 3620,
            ],
            [
                'id' => 67,
                'company_id' => 1,
                'name' => 'Salary cost Services',
                'parent_id' => 20,
                'type' => 'income',
                'sort' => 71,
                'account' => 5400,
            ],
            [
                'id' => 68,
                'company_id' => 1,
                'name' => 'Allowances Services',
                'parent_id' => 20,
                'type' => 'income',
                'sort' => 72,
                'account' => 5401,
            ],
            [
                'id' => 69,
                'company_id' => 1,
                'name' => 'Bonuses Services',
                'parent_id' => 20,
                'type' => 'income',
                'sort' => 73,
                'account' => 5402,
            ],
            [
                'id' => 70,
                'company_id' => 1,
                'name' => 'Commissions Services',
                'parent_id' => 20,
                'type' => 'income',
                'sort' => 74,
                'account' => 5403,
            ],
            [
                'id' => 71,
                'company_id' => 1,
                'name' => 'Social security benefits ',
                'parent_id' => 20,
                'type' => 'income',
                'sort' => 75,
                'account' => 5405,
            ],
            [
                'id' => 72,
                'company_id' => 1,
                'name' => 'Director Fees',
                'parent_id' => 20,
                'type' => 'income',
                'sort' => 76,
                'account' => 5409,
            ],
            [
                'id' => 73,
                'company_id' => 1,
                'name' => 'AHV, IV, EO, ALV',
                'parent_id' => 21,
                'type' => 'income',
                'sort' => 77,
                'account' => 5700,
            ],
            [
                'id' => 74,
                'company_id' => 1,
                'name' => 'FAK',
                'parent_id' => 21,
                'type' => 'income',
                'sort' => 78,
                'account' => 5710,
            ],
            [
                'id' => 75,
                'company_id' => 1,
                'name' => 'Occupational pension',
                'parent_id' => 21,
                'type' => 'income',
                'sort' => 79,
                'account' => 5720,
            ],
            [
                'id' => 76,
                'company_id' => 1,
                'name' => 'Accident insurance',
                'parent_id' => 21,
                'type' => 'income',
                'sort' => 80,
                'account' => 5730,
            ],
            [
                'id' => 77,
                'company_id' => 1,
                'name' => 'Daily sickness insurance',
                'parent_id' => 21,
                'type' => 'income',
                'sort' => 81,
                'account' => 5740,
            ],
            [
                'id' => 78,
                'company_id' => 1,
                'name' => 'Tax at source',
                'parent_id' => 21,
                'type' => 'income',
                'sort' => 82,
                'account' => 5790,
            ],
            [
                'id' => 79,
                'company_id' => 1,
                'name' => 'Staff recruitment',
                'parent_id' => 22,
                'type' => 'income',
                'sort' => 83,
                'account' => 5800,
            ],
            [
                'id' => 80,
                'company_id' => 1,
                'name' => 'Vocational education and traiding',
                'parent_id' => 22,
                'type' => 'income',
                'sort' => 84,
                'account' => 5810,
            ],
            [
                'id' => 81,
                'company_id' => 1,
                'name' => 'Other employee expenses',
                'parent_id' => 22,
                'type' => 'income',
                'sort' => 85,
                'account' => 5880,
            ],
            [
                'id' => 82,
                'company_id' => 1,
                'name' => 'Rent',
                'parent_id' => 23,
                'type' => 'income',
                'sort' => 86,
                'account' => 6000,
            ],
            [
                'id' => 83,
                'company_id' => 1,
                'name' => 'Expenses Furnishings and equipment',
                'parent_id' => 24,
                'type' => 'income',
                'sort' => 87,
                'account' => 6101,
            ],
            [
                'id' => 84,
                'company_id' => 1,
                'name' => 'Leasing tangible fixed assets',
                'parent_id' => 24,
                'type' => 'income',
                'sort' => 88,
                'account' => 6160,
            ],
            [
                'id' => 85,
                'company_id' => 1,
                'name' => 'Vehicle repair, service',
                'parent_id' => 25,
                'type' => 'income',
                'sort' => 89,
                'account' => 6200,
            ],
            [
                'id' => 86,
                'company_id' => 1,
                'name' => 'Vehicle fuel',
                'parent_id' => 25,
                'type' => 'income',
                'sort' => 90,
                'account' => 6210,
            ],
            [
                'id' => 87,
                'company_id' => 1,
                'name' => 'Vehicle insurance / vehicle tax',
                'parent_id' => 25,
                'type' => 'income',
                'sort' => 91,
                'account' => 6220,
            ],
            [
                'id' => 88,
                'company_id' => 1,
                'name' => 'Vehicle leasing',
                'parent_id' => 25,
                'type' => 'income',
                'sort' => 92,
                'account' => 6260,
            ],
            [
                'id' => 89,
                'company_id' => 1,
                'name' => 'Private share Vehicle expenses',
                'parent_id' => 25,
                'type' => 'income',
                'sort' => 93,
                'account' => 6270,
            ],
            [
                'id' => 90,
                'company_id' => 1,
                'name' => 'Insurance premiums',
                'parent_id' => 26,
                'type' => 'income',
                'sort' => 94,
                'account' => 6300,
            ],
            [
                'id' => 91,
                'company_id' => 1,
                'name' => 'Duties and charges',
                'parent_id' => 26,
                'type' => 'income',
                'sort' => 95,
                'account' => 6360,
            ],
            [
                'id' => 92,
                'company_id' => 1,
                'name' => 'Electricity/water/gas',
                'parent_id' => 27,
                'type' => 'income',
                'sort' => 96,
                'account' => 6400,
            ],
            [
                'id' => 93,
                'company_id' => 1,
                'name' => 'Office material',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 97,
                'account' => 6500,
            ],
            [
                'id' => 94,
                'company_id' => 1,
                'name' => 'Magazines, books',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 98,
                'account' => 6503,
            ],
            [
                'id' => 95,
                'company_id' => 1,
                'name' => 'Telephone, internet',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 99,
                'account' => 6510,
            ],
            [
                'id' => 96,
                'company_id' => 1,
                'name' => 'Postage',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 100,
                'account' => 6513,
            ],
            [
                'id' => 97,
                'company_id' => 1,
                'name' => 'Contributions, donations',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 101,
                'account' => 6520,
            ],
            [
                'id' => 98,
                'company_id' => 1,
                'name' => 'Accounting expenses',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 102,
                'account' => 6530,
            ],
            [
                'id' => 99,
                'company_id' => 1,
                'name' => 'Legal consulting',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 103,
                'account' => 6531,
            ],
            [
                'id' => 100,
                'company_id' => 1,
                'name' => 'Tax consulting',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 104,
                'account' => 6532,
            ],
            [
                'id' => 101,
                'company_id' => 1,
                'name' => 'Other consulting expenses',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 105,
                'account' => 6533,
            ],
            [
                'id' => 102,
                'company_id' => 1,
                'name' => 'Gsuites expenses',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 106,
                'account' => 6540,
            ],
            [
                'id' => 103,
                'company_id' => 1,
                'name' => 'Cloud Storage expenses',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 107,
                'account' => 6550,
            ],
            [
                'id' => 104,
                'company_id' => 1,
                'name' => 'Leasing and rent HW + SW',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 108,
                'account' => 6560,
            ],
            [
                'id' => 105,
                'company_id' => 1,
                'name' => 'Licenses and maintenance',
                'parent_id' => 28,
                'type' => 'income',
                'sort' => 109,
                'account' => 6570,
            ],
            [
                'id' => 106,
                'company_id' => 1,
                'name' => 'Advertising',
                'parent_id' => 29,
                'type' => 'income',
                'sort' => 110,
                'account' => 6600,
            ],
            [
                'id' => 107,
                'company_id' => 1,
                'name' => 'Promotional print material',
                'parent_id' => 29,
                'type' => 'income',
                'sort' => 111,
                'account' => 6610,
            ],
            [
                'id' => 108,
                'company_id' => 1,
                'name' => 'Exhibitions / decoration',
                'parent_id' => 29,
                'type' => 'income',
                'sort' => 112,
                'account' => 6620,
            ],
            [
                'id' => 109,
                'company_id' => 1,
                'name' => 'Web Hostung services',
                'parent_id' => 29,
                'type' => 'income',
                'sort' => 113,
                'account' => 6630,
            ],
            [
                'id' => 110,
                'company_id' => 1,
                'name' => 'Travel expenses',
                'parent_id' => 29,
                'type' => 'income',
                'sort' => 114,
                'account' => 6640,
            ],
            [
                'id' => 111,
                'company_id' => 1,
                'name' => 'Representation expenses ',
                'parent_id' => 29,
                'type' => 'income',
                'sort' => 115,
                'account' => 6641,
            ],
            [
                'id' => 112,
                'company_id' => 1,
                'name' => 'Customer gifts',
                'parent_id' => 29,
                'type' => 'income',
                'sort' => 116,
                'account' => 6642,
            ],
            [
                'id' => 113,
                'company_id' => 1,
                'name' => 'Other expenses',
                'parent_id' => 30,
                'type' => 'income',
                'sort' => 117,
                'account' => 6700,
            ],
            [
                'id' => 114,
                'company_id' => 1,
                'name' => 'Depreciation on financial assets',
                'parent_id' => 31,
                'type' => 'income',
                'sort' => 118,
                'account' => 6800,
            ],
            [
                'id' => 115,
                'company_id' => 1,
                'name' => 'Depreciation on machinery and appliances',
                'parent_id' => 31,
                'type' => 'income',
                'sort' => 119,
                'account' => 6820,
            ],
            [
                'id' => 116,
                'company_id' => 1,
                'name' => 'Depreciation on furniture and equipment',
                'parent_id' => 31,
                'type' => 'income',
                'sort' => 120,
                'account' => 6821,
            ],
            [
                'id' => 117,
                'company_id' => 1,
                'name' => 'Depreciation on office equipment and computers',
                'parent_id' => 31,
                'type' => 'income',
                'sort' => 121,
                'account' => 6822,
            ],
            [
                'id' => 118,
                'company_id' => 1,
                'name' => 'Depreciation on vehicles',
                'parent_id' => 31,
                'type' => 'income',
                'sort' => 122,
                'account' => 6823,
            ],
            [
                'id' => 119,
                'company_id' => 1,
                'name' => 'Depreciation on immovable fixes assets',
                'parent_id' => 31,
                'type' => 'income',
                'sort' => 123,
                'account' => 6830,
            ],
            [
                'id' => 120,
                'company_id' => 1,
                'name' => 'Depreciation on intangible assets',
                'parent_id' => 31,
                'type' => 'income',
                'sort' => 124,
                'account' => 6840,
            ],
            [
                'id' => 121,
                'company_id' => 1,
                'name' => 'Depreciation on capitalized expenditure',
                'parent_id' => 31,
                'type' => 'income',
                'sort' => 125,
                'account' => 6850,
            ],
            [
                'id' => 122,
                'company_id' => 1,
                'name' => 'Interest expenses on loans',
                'parent_id' => 32,
                'type' => 'income',
                'sort' => 126,
                'account' => 6901,
            ],
            [
                'id' => 123,
                'company_id' => 1,
                'name' => 'Other Bank Charges',
                'parent_id' => 32,
                'type' => 'income',
                'sort' => 127,
                'account' => 6940,
            ],
            [
                'id' => 124,
                'company_id' => 1,
                'name' => 'Exchange losses',
                'parent_id' => 32,
                'type' => 'income',
                'sort' => 128,
                'account' => 6949,
            ],
            [
                'id' => 125,
                'company_id' => 1,
                'name' => 'Rental income',
                'parent_id' => 33,
                'type' => 'income',
                'sort' => 129,
                'account' => 7500,
            ],
            [
                'id' => 126,
                'company_id' => 1,
                'name' => 'Property expenses',
                'parent_id' => 33,
                'type' => 'income',
                'sort' => 130,
                'account' => 7510,
            ],
            [
                'id' => 127,
                'company_id' => 1,
                'name' => 'Gains on tangible fixed assets',
                'parent_id' => 34,
                'type' => 'income',
                'sort' => 131,
                'account' => 7910,
            ],
            [
                'id' => 128,
                'company_id' => 1,
                'name' => 'Non-company related expenditures',
                'parent_id' => 35,
                'type' => 'income',
                'sort' => 132,
                'account' => 8000,
            ],
            [
                'id' => 129,
                'company_id' => 1,
                'name' => 'Non-company related income',
                'parent_id' => 36,
                'type' => 'income',
                'sort' => 133,
                'account' => 8100,
            ],
            [
                'id' => 130,
                'company_id' => 1,
                'name' => 'Cantonal and municipal taxes',
                'parent_id' => 37,
                'type' => 'income',
                'sort' => 134,
                'account' => 8900,
            ],
            [
                'id' => 131,
                'company_id' => 1,
                'name' => 'Direct federal taxes',
                'parent_id' => 38,
                'type' => 'income',
                'sort' => 135,
                'account' => 8901,
            ]
        ];

        DB::table('categories')->insert($categories);

        $update = [
            'created_at' => now(),
            'updated_at' => now()
        ];

        DB::table('categories')->update($update);
    }
}
