<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategoryBalanceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            [
                'id' => 132,
                'company_id' => 1,
                'name' => 'Current Assets',
                'format' => 'currency',
                'parent_id' => null,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 1,
                'account' => null,
            ],
            [
                'id' => 133,
                'company_id' => 1,
                'name' => 'Fixed Assets',
                'format' => 'currency',
                'parent_id' => null,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 2,
                'account' => null,
            ],
            [
                'id' => 134,
                'company_id' => 1,
                'name' => 'Short-term Liabilites',
                'format' => 'currency',
                'parent_id' => null,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 3,
                'account' => null,
            ],
            [
                'id' => 135,
                'company_id' => 1,
                'name' => 'Long-Term Liabilites',
                'format' => 'currency',
                'parent_id' => null,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 4,
                'account' => null,
            ],
            [
                'id' => 136,
                'company_id' => 1,
                'name' => 'Equity',
                'format' => 'currency',
                'parent_id' => null,
                'group_id' => 7,
                'type' => 'balance',
                'sort' => 5,
                'account' => null,
            ],
            [
                'id' => 137,
                'company_id' => 1,
                'name' => 'Cash and cash equivalents ',
                'format' => 'currency',
                'parent_id' => 132,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 6,
                'account' => null,
            ],
            [
                'id' => 138,
                'company_id' => 1,
                'name' => 'Short-term Assets listed Stock Exchange',
                'format' => 'currency',
                'parent_id' => 132,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 7,
                'account' => null,
            ],
            [
                'id' => 139,
                'company_id' => 1,
                'name' => 'Accounts receivable trade and services',
                'format' => 'currency',
                'parent_id' => 132,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 8,
                'account' => null,
            ],
            [
                'id' => 140,
                'company_id' => 1,
                'name' => 'Other short-term reveivables ',
                'format' => 'currency',
                'parent_id' => 132,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 9,
                'account' => null,
            ],
            [
                'id' => 141,
                'company_id' => 1,
                'name' => 'Prepaid Expenses ',
                'format' => 'currency',
                'parent_id' => 132,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 10,
                'account' => null,
            ],
            [
                'id' => 142,
                'company_id' => 1,
                'name' => 'Financial assets ',
                'format' => 'currency',
                'parent_id' => 133,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 11,
                'account' => null,
            ],
            [
                'id' => 143,
                'company_id' => 1,
                'name' => 'Investments ',
                'format' => 'currency',
                'parent_id' => 133,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 12,
                'account' => null,
            ],
            [
                'id' => 144,
                'company_id' => 1,
                'name' => 'Tangible assets ',
                'format' => 'currency',
                'parent_id' => 133,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 13,
                'account' => null,
            ],
            [
                'id' => 145,
                'company_id' => 1,
                'name' => 'Intangible fixed assets ',
                'format' => 'currency',
                'parent_id' => 133,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 14,
                'account' => null,
            ],
            [
                'id' => 146,
                'company_id' => 1,
                'name' => 'Capital or non-paid Foundation capital',
                'format' => 'currency',
                'parent_id' => 133,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 15,
                'account' => null,
            ],
            [
                'id' => 147,
                'company_id' => 1,
                'name' => 'Suppliers or creditors ',
                'format' => 'currency',
                'parent_id' => 134,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 16,
                'account' => null,
            ],
            [
                'id' => 148,
                'company_id' => 1,
                'name' => 'Short-term onorous debts ',
                'format' => 'currency',
                'parent_id' => 134,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 17,
                'account' => null,
            ],
            [
                'id' => 149,
                'company_id' => 1,
                'name' => 'Other short-term debts ',
                'format' => 'currency',
                'parent_id' => 134,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 18,
                'account' => null,
            ],
            [
                'id' => 150,
                'company_id' => 1,
                'name' => 'Other short-term debts social insurances',
                'format' => 'currency',
                'parent_id' => 134,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 19,
                'account' => null,
            ],
            [
                'id' => 151,
                'company_id' => 1,
                'name' => 'Accruals and deferred income ',
                'format' => 'currency',
                'parent_id' => 135,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 20,
                'account' => null,
            ],
            [
                'id' => 152,
                'company_id' => 1,
                'name' => 'Long-term onorous debts ',
                'format' => 'currency',
                'parent_id' => 135,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 21,
                'account' => null,
            ],
            [
                'id' => 153,
                'company_id' => 1,
                'name' => 'Other long-term debts ',
                'format' => 'currency',
                'parent_id' => 135,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 22,
                'account' => null,
            ],
            [
                'id' => 154,
                'company_id' => 1,
                'name' => 'Provisions ',
                'format' => 'currency',
                'parent_id' => 135,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 23,
                'account' => null,
            ],
            [
                'id' => 155,
                'company_id' => 1,
                'name' => 'Capital or Capital of the foundation',
                'format' => 'currency',
                'parent_id' => 136,
                'group_id' => 7,
                'type' => 'balance',
                'sort' => 24,
                'account' => null,
            ],
            [
                'id' => 156,
                'company_id' => 1,
                'name' => 'Legal Reserves, Profit or Loss',
                'format' => 'currency',
                'parent_id' => 136,
                'group_id' => 7,
                'type' => 'balance',
                'sort' => 25,
                'account' => null,
            ],
            [
                'id' => 157,
                'company_id' => 1,
                'name' => 'Cash on hand',
                'format' => 'currency',
                'parent_id' => 137,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 26,
                'account' => 1000,
            ],
            [
                'id' => 158,
                'company_id' => 1,
                'name' => 'EFG Bank',
                'format' => 'currency',
                'parent_id' => 137,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 27,
                'account' => 1010,
            ],
            [
                'id' => 159,
                'company_id' => 1,
                'name' => 'CIM Banque CHF',
                'format' => 'currency',
                'parent_id' => 137,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 28,
                'account' => 1020,
            ],
            [
                'id' => 160,
                'company_id' => 1,
                'name' => 'CIM Banque EUR',
                'format' => 'currency',
                'parent_id' => 137,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 29,
                'account' => 1030,
            ],
            [
                'id' => 161,
                'company_id' => 1,
                'name' => 'CIM Banque USD',
                'format' => 'currency',
                'parent_id' => 137,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 30,
                'account' => 1040,
            ],
            [
                'id' => 162,
                'company_id' => 1,
                'name' => 'Time deposits',
                'format' => 'currency',
                'parent_id' => 137,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 31,
                'account' => 1050,
            ],
            [
                'id' => 163,
                'company_id' => 1,
                'name' => 'Securities',
                'format' => 'currency',
                'parent_id' => 138,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 32,
                'account' => 1060,
            ],
            [
                'id' => 164,
                'company_id' => 1,
                'name' => 'Fund transfer account',
                'format' => 'currency',
                'parent_id' => 138,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 33,
                'account' => 1090,
            ],
            [
                'id' => 165,
                'company_id' => 1,
                'name' => 'Accounts receivable trade and services',
                'format' => 'currency',
                'parent_id' => 139,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 34,
                'account' => 1100,
            ],
            [
                'id' => 166,
                'company_id' => 1,
                'name' => 'Accounts receivable EUR',
                'format' => 'currency',
                'parent_id' => 139,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 35,
                'account' => 1105,
            ],
            [
                'id' => 167,
                'company_id' => 1,
                'name' => 'Employee account revceivables',
                'format' => 'currency',
                'parent_id' => 140,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 36,
                'account' => 1120,
            ],
            [
                'id' => 168,
                'company_id' => 1,
                'name' => 'Advances and loans',
                'format' => 'currency',
                'parent_id' => 140,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 37,
                'account' => 1140,
            ],
            [
                'id' => 169,
                'company_id' => 1,
                'name' => 'Input tax on cost of material and services',
                'format' => 'currency',
                'parent_id' => 140,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 38,
                'account' => 1170,
            ],
            [
                'id' => 170,
                'company_id' => 1,
                'name' => 'Input tax on investments and other ',
                'format' => 'currency',
                'parent_id' => 140,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 39,
                'account' => 1171,
            ],
            [
                'id' => 171,
                'company_id' => 1,
                'name' => 'Other short-term receivables',
                'format' => 'currency',
                'parent_id' => 140,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 40,
                'account' => 1190,
            ],
            [
                'id' => 172,
                'company_id' => 1,
                'name' => 'Advance payments',
                'format' => 'currency',
                'parent_id' => 140,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 41,
                'account' => 1192,
            ],
            [
                'id' => 173,
                'company_id' => 1,
                'name' => 'Prepaid expenses',
                'format' => 'currency',
                'parent_id' => 141,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 42,
                'account' => 1300,
            ],
            [
                'id' => 174,
                'company_id' => 1,
                'name' => 'Insurance',
                'format' => 'currency',
                'parent_id' => 141,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 43,
                'account' => 1310,
            ],
            [
                'id' => 175,
                'company_id' => 1,
                'name' => 'Annual Subscripton 1',
                'format' => 'currency',
                'parent_id' => 141,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 44,
                'account' => 1320,
            ],
            [
                'id' => 176,
                'company_id' => 1,
                'name' => 'Annual Subscripton 2',
                'format' => 'currency',
                'parent_id' => 141,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 45,
                'account' => 1330,
            ],
            [
                'id' => 177,
                'company_id' => 1,
                'name' => 'Securities',
                'format' => 'currency',
                'parent_id' => 142,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 46,
                'account' => 1400,
            ],
            [
                'id' => 178,
                'company_id' => 1,
                'name' => 'VA Securities',
                'format' => 'currency',
                'parent_id' => 142,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 47,
                'account' => 1409,
            ],
            [
                'id' => 179,
                'company_id' => 1,
                'name' => 'Securities to market value',
                'format' => 'currency',
                'parent_id' => 142,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 48,
                'account' => 1410,
            ],
            [
                'id' => 180,
                'company_id' => 1,
                'name' => 'Bonds',
                'format' => 'currency',
                'parent_id' => 142,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 49,
                'account' => 1403,
            ],
            [
                'id' => 181,
                'company_id' => 1,
                'name' => 'Loans',
                'format' => 'currency',
                'parent_id' => 142,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 50,
                'account' => 1440,
            ],
            [
                'id' => 182,
                'company_id' => 1,
                'name' => 'Mortgages',
                'format' => 'currency',
                'parent_id' => 142,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 51,
                'account' => 1441,
            ],
            [
                'id' => 183,
                'company_id' => 1,
                'name' => 'Holdings',
                'format' => 'currency',
                'parent_id' => 143,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 52,
                'account' => 1480,
            ],
            [
                'id' => 184,
                'company_id' => 1,
                'name' => 'VA Holdings',
                'format' => 'currency',
                'parent_id' => 143,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 53,
                'account' => 1489,
            ],
            [
                'id' => 185,
                'company_id' => 1,
                'name' => 'Movable property, furnishings',
                'format' => 'currency',
                'parent_id' => 144,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 54,
                'account' => 1510,
            ],
            [
                'id' => 186,
                'company_id' => 1,
                'name' => 'Office machinery, computers, communication',
                'format' => 'currency',
                'parent_id' => 144,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 55,
                'account' => 1520,
            ],
            [
                'id' => 187,
                'company_id' => 1,
                'name' => 'Vehicles',
                'format' => 'currency',
                'parent_id' => 144,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 56,
                'account' => 1530,
            ],
            [
                'id' => 188,
                'company_id' => 1,
                'name' => 'Patents',
                'format' => 'currency',
                'parent_id' => 145,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 57,
                'account' => 1700,
            ],
            [
                'id' => 189,
                'company_id' => 1,
                'name' => 'Know-how',
                'format' => 'currency',
                'parent_id' => 145,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 58,
                'account' => 1701,
            ],
            [
                'id' => 190,
                'company_id' => 1,
                'name' => 'Licenses',
                'format' => 'currency',
                'parent_id' => 145,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 59,
                'account' => 1720,
            ],
            [
                'id' => 191,
                'company_id' => 1,
                'name' => 'Goodwill',
                'format' => 'currency',
                'parent_id' => 145,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 60,
                'account' => 1770,
            ],
            [
                'id' => 192,
                'company_id' => 1,
                'name' => 'Share capital, not paid in',
                'format' => 'currency',
                'parent_id' => 146,
                'group_id' => 5,
                'type' => 'balance',
                'sort' => 61,
                'account' => 1850,
            ],
            [
                'id' => 193,
                'company_id' => 1,
                'name' => 'Payables (Accounts payable)',
                'format' => 'currency',
                'parent_id' => 147,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 62,
                'account' => 2000,
            ],
            [
                'id' => 194,
                'company_id' => 1,
                'name' => 'Payables EUR',
                'format' => 'currency',
                'parent_id' => 147,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 63,
                'account' => 2005,
            ],
            [
                'id' => 195,
                'company_id' => 1,
                'name' => 'Advance payments from customers',
                'format' => 'currency',
                'parent_id' => 147,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 64,
                'account' => 2030,
            ],
            [
                'id' => 196,
                'company_id' => 1,
                'name' => 'Due to banks, short-term',
                'format' => 'currency',
                'parent_id' => 148,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 65,
                'account' => 2100,
            ],
            [
                'id' => 197,
                'company_id' => 1,
                'name' => 'Financial leasing payables',
                'format' => 'currency',
                'parent_id' => 148,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 66,
                'account' => 2120,
            ],
            [
                'id' => 198,
                'company_id' => 1,
                'name' => 'Other interest-bearing liabilities',
                'format' => 'currency',
                'parent_id' => 148,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 67,
                'account' => 2140,
            ],
            [
                'id' => 199,
                'company_id' => 1,
                'name' => 'Shareholder liabilities',
                'format' => 'currency',
                'parent_id' => 148,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 68,
                'account' => 2160,
            ],
            [
                'id' => 200,
                'company_id' => 1,
                'name' => 'Turnover tax',
                'format' => 'currency',
                'parent_id' => 149,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 69,
                'account' => 2200,
            ],
            [
                'id' => 201,
                'company_id' => 1,
                'name' => 'VAT payment account',
                'format' => 'currency',
                'parent_id' => 149,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 70,
                'account' => 2201,
            ],
            [
                'id' => 202,
                'company_id' => 1,
                'name' => 'Other short-term payables',
                'format' => 'currency',
                'parent_id' => 149,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 71,
                'account' => 2210,
            ],
            [
                'id' => 203,
                'company_id' => 1,
                'name' => 'Due to BVG',
                'format' => 'currency',
                'parent_id' => 150,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 72,
                'account' => 2270,
            ],
            [
                'id' => 204,
                'company_id' => 1,
                'name' => 'Due to AHV/ALV',
                'format' => 'currency',
                'parent_id' => 150,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 73,
                'account' => 2271,
            ],
            [
                'id' => 205,
                'company_id' => 1,
                'name' => 'Due to FAK',
                'format' => 'currency',
                'parent_id' => 150,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 74,
                'account' => 2272,
            ],
            [
                'id' => 206,
                'company_id' => 1,
                'name' => 'Due to UVG',
                'format' => 'currency',
                'parent_id' => 150,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 75,
                'account' => 2273,
            ],
            [
                'id' => 207,
                'company_id' => 1,
                'name' => 'Due to KVG',
                'format' => 'currency',
                'parent_id' => 150,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 76,
                'account' => 2274,
            ],
            [
                'id' => 208,
                'company_id' => 1,
                'name' => 'Tax at source due',
                'format' => 'currency',
                'parent_id' => 150,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 77,
                'account' => 2279,
            ],
            [
                'id' => 209,
                'company_id' => 1,
                'name' => 'Transitory payroll account',
                'format' => 'currency',
                'parent_id' => 150,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 78,
                'account' => 2280,
            ],
            [
                'id' => 210,
                'company_id' => 1,
                'name' => 'Unpaid expenses',
                'format' => 'currency',
                'parent_id' => 151,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 79,
                'account' => 2300,
            ],
            [
                'id' => 211,
                'company_id' => 1,
                'name' => 'Short-term provisions restoration and repairs',
                'format' => 'currency',
                'parent_id' => 151,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 80,
                'account' => 2330,
            ],
            [
                'id' => 212,
                'company_id' => 1,
                'name' => 'Bank liabilities',
                'format' => 'currency',
                'parent_id' => 152,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 81,
                'account' => 2400,
            ],
            [
                'id' => 213,
                'company_id' => 1,
                'name' => 'Liabilities from financial leasing contracts',
                'format' => 'currency',
                'parent_id' => 152,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 82,
                'account' => 2420,
            ],
            [
                'id' => 214,
                'company_id' => 1,
                'name' => 'Loans',
                'format' => 'currency',
                'parent_id' => 152,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 83,
                'account' => 2450,
            ],
            [
                'id' => 215,
                'company_id' => 1,
                'name' => 'Mortgage on commercial property',
                'format' => 'currency',
                'parent_id' => 152,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 84,
                'account' => 2451,
            ],
            [
                'id' => 216,
                'company_id' => 1,
                'name' => 'Loans',
                'format' => 'currency',
                'parent_id' => 153,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 85,
                'account' => 2500,
            ],
            [
                'id' => 217,
                'company_id' => 1,
                'name' => 'Provisions',
                'format' => 'currency',
                'parent_id' => 154,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 86,
                'account' => 2600,
            ],
            [
                'id' => 218,
                'company_id' => 1,
                'name' => 'Provisions for warranties',
                'format' => 'currency',
                'parent_id' => 154,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 87,
                'account' => 2630,
            ],
            [
                'id' => 219,
                'company_id' => 1,
                'name' => 'Provisions for deferred taxes',
                'format' => 'currency',
                'parent_id' => 154,
                'group_id' => 6,
                'type' => 'balance',
                'sort' => 88,
                'account' => 2640,
            ],
            [
                'id' => 220,
                'company_id' => 1,
                'name' => 'Share capital',
                'format' => 'currency',
                'parent_id' => 155,
                'group_id' => 7,
                'type' => 'balance',
                'sort' => 89,
                'account' => 2800,
            ],
            [
                'id' => 221,
                'company_id' => 1,
                'name' => 'Legal capital reserves',
                'format' => 'currency',
                'parent_id' => 156,
                'group_id' => 7,
                'type' => 'balance',
                'sort' => 90,
                'account' => 2900,
            ],
            [
                'id' => 222,
                'company_id' => 1,
                'name' => 'Provisions for own shares of capital',
                'format' => 'currency',
                'parent_id' => 156,
                'group_id' => 7,
                'type' => 'balance',
                'sort' => 91,
                'account' => 2930,
            ],
            [
                'id' => 223,
                'company_id' => 1,
                'name' => 'Revaluation reserve',
                'format' => 'currency',
                'parent_id' => 156,
                'group_id' => 7,
                'type' => 'balance',
                'sort' => 92,
                'account' => 2940,
            ],
            [
                'id' => 224,
                'company_id' => 1,
                'name' => 'Legal reserve Retained earnings',
                'format' => 'currency',
                'parent_id' => 156,
                'group_id' => 7,
                'type' => 'balance',
                'sort' => 93,
                'account' => 2950,
            ],
            [
                'id' => 225,
                'company_id' => 1,
                'name' => 'Optional reserves on earnings',
                'format' => 'currency',
                'parent_id' => 156,
                'group_id' => 7,
                'type' => 'balance',
                'sort' => 94,
                'account' => 2960,
            ],
            [
                'id' => 226,
                'company_id' => 1,
                'name' => 'Earned Surplus carr. forward or loss carried forward',
                'format' => 'currency',
                'parent_id' => 156,
                'group_id' => 7,
                'type' => 'balance',
                'sort' => 95,
                'account' => 2970,
            ],
            [
                'id' => 227,
                'company_id' => 1,
                'name' => 'Annual profit or annual loss',
                'format' => 'currency',
                'parent_id' => 156,
                'group_id' => 7,
                'type' => 'balance',
                'sort' => 96,
                'account' => 2979,
            ],
            [
                'id' => 228,
                'company_id' => 1,
                'name' => 'Treasury shares',
                'format' => 'currency',
                'parent_id' => 156,
                'group_id' => 7,
                'type' => 'balance',
                'sort' => 97,
                'account' => 2980,
            ]
        ];

        DB::table('categories')->insert($categories);

        $update = [
            'created_at' => now(),
            'updated_at' => now()
        ];

        DB::table('categories')->update($update);
    }
}
